name: Embed code in README

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  embed-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.MY_ACCESS_TOKEN }}
          persist-credentials: false
          fetch-depth: 0
          ref: refs/heads/${{ github.head_ref }}

      - uses: tokusumi/markdown-embed-code@main
        with:
          markdown: "README.md"
          token: ${{ secrets.MY_ACCESS_TOKEN }}
          message: "synchronizing Readme"
          silent: false